CC = g++
CFLAGS = -lGL -lglut

example:	
	$(CC) $(CFLAGS) main.cpp visuals.cpp visuals.h -o lab1.o

task1:
	$(CC) $(CFLAGS) main.cpp assignment1.cpp assignment1.h visuals.h -o task1.o

clean:
	rm -f *.o *~

